const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
const LOAD_PRODUCTS_LOADING = 'LOAD_PRODUCTS_LOADING';
const LOAD_PRODUCTS_ALL = 'LOAD_PRODUCTS_ALL';

const ADD_TO_CART = 'ADD_TO_CART';

const LOAD_PRODUCT = 'LOAD_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

export {
  LOAD_PRODUCTS,
  LOAD_PRODUCTS_SUCCESS,
  LOAD_PRODUCTS_LOADING,
  LOAD_PRODUCTS_ALL,
  ADD_TO_CART,
  LOAD_PRODUCT,
  REMOVE_PRODUCT
};
